# Generated by Django 5.1.2 on 2024-10-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBLusuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('senha', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
